auth/urls.py
from django.urls import path
from auth import views

urlpatterns = [
    path('register/', views.register_request, name="register"),
    path('login/', views.login_request, name="login"),
    path('logout/', views.logout_request, name="logout"),
]

main/urls.py
from django.urls import path
from . import views
from .api import DirectoryAPI, EditAPI



urlpatterns = [
    path('', views.home, name="home"),
    path('dashboard/<str:dir>', views.dashboard_view, name="dashboard"),
    path('edit/<str:dir>', views.edit_view, name="edit"),
    path('api/<int:dir>', DirectoryAPI.as_view(), name="directory_api"),
    path('edit/api/<int:dir>', EditAPI.as_view(), name="edit_api"),
]

pixlr/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth.urls')),
    path('', include('main.urls')),
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Directory(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    directory_name = models.CharField(max_length=50)
    parent_directory = models.ForeignKey("self", null=True, on_delete=models.CASCADE)
    image_path = models.ImageField(null=True, default=None ,upload_to='images/')
    is_directory = models.BooleanField(default=1, null=False)

main/forms.py
# forms.py
from django import forms
from .models import *
  
class ImageForm(forms.ModelForm):
  
    class Meta:
        model = Directory
        fields = ['directory_name', 'image_path']
        labels = {
        "directory_name": "Name",
        "image_path" : "Choose Image"
    }

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Directory
from .forms import *
from django.contrib import messages


def home(request):

    if request.user.is_authenticated:
        home_dir = Directory.objects.filter(user_id=request.user, directory_name="home")
        print(home_dir)
        home_dir = home_dir[0].pk
    else:
        home_dir = -1
    return render(request, template_name="home.html", context={"title" : "Home","home_dir" : home_dir})


@login_required(login_url='/auth/login/')
def dashboard_view(request, dir):
    
    try:
        parent_dir = Directory.objects.get(pk=dir)
        dirs = Directory.objects.filter(user_id_id=request.user, parent_directory=parent_dir)
        if len(dirs) == 0:
            dirs = None
    except Directory.DoesNotExist:
        messages.error(request, "Cannot Locate the DIR, Try Again!")
        return redirect("/")

    if parent_dir.user_id != request.user:
        messages.error(request, "You Do Not Have Permissions To That DIR.")
        return redirect("/")

    context = {
        "title" : "Dashboard",
        "home_dir" : parent_dir,
        "dirs" : dirs,
    }
    return render(request, template_name="dashboard.html", context=context)


@login_required(login_url='/auth/login/')
def edit_view(request, dir):
    
    try:
        image = Directory.objects.get(pk=dir)
    except Directory.DoesNotExist:
        image = None

    parent_dir = Directory.objects.get(pk=dir)

    context = {
        "title" : "Edit Image",
        "image" : image,
        "home_dir" : parent_dir,
    }
    return render(request, template_name="edit.html", context=context)

templates/dashboard.html
{% extends "header.html" %}

{% block content %} 

{% load static %}
{% load crispy_forms_tags %}         
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
<style>
    .box{
        display:flex;
        align-items:center;
        justify-content:center;
        flex-direction:column;
        width:120px;
        height:140px;
        padding:20px;
        font-size:20px;
        margin:10px;
    }
    .delete{
        display:none;
        color:red;
    }
    .modal_delete:hover{
        color:red;
    }
    .box:hover{
        transform: scale(0.97);
    }
    .box:hover .delete{
        display:block;
    }
    .delete:hover{
        transform: scale(1.2);
    }

</style>
<div class="mt-5">
	<div class="row" >
			<div class="col-md-3 mt-2">
				<div class="d-flex flex-column justify-content-start align-items-center glass pb-4" style="height:80vh;">
                    <img class="img-responsive mb-4 mt-5" style="width:30%;" src="{% static 'img/lens2.png' %}" alt="LOGO">
					<h1 class="text-center">📸</h1>

                    <h4 class="text-center">Welcome {{user.username}}</h4>
                    <h4 class="text-center" style="margin-top:50px;"><a href="{% url 'logout' %}" class="btn custom-btn"><span class="fas fa-sign-out-alt"></span> Logout</a></h4>
				</div>
			</div>
			<div class="col-md-9 mt-2">
				
				<div class="glass" style="min-height:80vh;">
                    <div class="row d-flex justify-content-center" style="padding:20px;" id="top">
                        <div class="col-md-2 btn btn-lg custom-btn mx-3 mt-3" style="background:grey;" onclick="window.history.back()"><span class="fas fa-arrow-left"></span> Return</div>                        
                        <div data-bs-toggle="modal" data-bs-target="#uploadModal" class="col-md-2 btn btn-lg custom-btn mx-3 mt-3" style="background:var(--primary);" ><span class="fas fa-upload"></span> Upload Image</div>
                        <div data-bs-toggle="modal" data-bs-target="#folderModal" class="col-md-2 btn btn-lg custom-btn mx-3 mt-3" style="background:rgb(28, 172, 28);" ><span class="fas fa-folder"></span> New Folder</div>
                        
                    </div>
                    <hr style="height:2px;margin:10px;" class="">
                    <div class="row d-flex flex-row justify-content-center mt-3" id="top">
                        <h4>Current Directory : {{home_dir.directory_name | title }}</h4>
                    </div>
                    
					<div class="row d-flex flex-row justify-content-start enclose" style="padding:50px;" id="main">

                        {% for dir in dirs %}                           
                            {% if dir.is_directory %}
                            <div id="{{dir.pk}}" ondblclick="navigate(event,'{% url 'dashboard' dir=dir.pk %}')" class="glass box">
                                <div onclick="delete_node(event)" class="delete fas fa-times-circle" style="margin-bottom:20px;"></div>
                                <span class="fas fa-folder"></span>
                                <div id="name{{dir.pk}}">{{dir.directory_name | title}}</div>
                            </div>
                            {% else %}
                            <div id="{{dir.pk}}" ondblclick="navigate(event,'{% url 'edit' dir=dir.pk %}')" class="glass box bg-primary text-white">
                                <div onclick="delete_node(event)" class="delete fas fa-times-circle" style="margin-bottom:20px;color:tomato"></div>
                                <span class=" fas fa-file"></span>
                                <div id="name{{dir.pk}}">{{dir.directory_name | title}}</div>
                            </div>
                            {% endif %}
                        {% endfor %}  
                    </div>
				</div>
			</div>
		
	</div>
</div>

  
<!-- Modal -->
<div class="modal fade" id="uploadModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content glass">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel">UPLOAD IMAGE</h4>
                <div style="font-size:25px;" id="close_upload" class=" modal_delete fas fa-times-circle" data-bs-dismiss="modal" aria-label="Close"></div>
            </div>
        <div class="modal-body">
            <div class="form-group col-md-8" id="form_upload">
                <label for="directory_name">Image Name*</label>
                <input class="form-control" type="text" id="id_directory_name" name="directory_name" required>
                <label class="mt-3" for="image_path">Choose File*</label>
                <input style="background-color: transparent;padding:0px;border:0px;" class="form-control-file" type="file" id="id_image_path" name='image_path' accept="image/*" required>
                <div class="form-group mt-4">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button id="submit_upload" onclick="upload_image(event)" type="submit" class="btn btn-primary">Upload</button>
                </div>
            </div>  
        </div>
        
        </div>
    </div>
</div>


<div class="modal fade" id="folderModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content glass">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel">CREATE FOLDER</h4>
                <div style="font-size:25px;" id="close_create" class=" modal_delete fas fa-times-circle" data-bs-dismiss="modal" aria-label="Close"></div>
            </div>
        <div class="modal-body">
            <div class="form-group" id="form_upload">
                <label for="directory_name">Folder Name</label>
                <input class="form-control" type="text" id="id_directory_name2" name="directory_name" required>
                <div class="form-group mt-4">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button id="submit_folder" onclick="create_folder()" type="submit" class="btn btn-primary">Create</button>
                </div>
            </div>  
        </div>
        
        </div>
    </div>
</div>


<script>
    var upload_file_url = "/api/{{home_dir.pk}}"
    var token = '{{csrf_token}}';
    var formData = new FormData()
    const input = document.getElementById('id_image_path');

    const upload_image = () => {
        formData.append("directory_name", document.getElementById('id_directory_name').value)
        formData.append("image_path", input.files[0])

        
        fetch(upload_file_url, { // Your POST endpoint
          method: 'POST',
          headers: {
            "X-CSRFToken": token,
            "Accept":'application/json'
          },
          body: formData // This is your file object
        }).then(
          response => response.json() // if the response is a JSON object
        ).then(
          (json) => {
                message(json.info, "info")
                if(json.info == 'Image Uploaded Successfully'){
                  create_ui(json.dir, json.directory_name, false)
                }
                $('#close_upload').trigger('click')
                console.log(json)
          }
        ).catch(
          error => console.log(error) // Handle the error response object
        );
      };

      const create_folder = () => {

        fetch(upload_file_url, { // Your POST endpoint
          method: 'PUT',
          headers: {
            "X-CSRFToken": token,
            "Accept":'application/json',
            "Content-Type":'application/json',  
          },
          body:JSON.stringify({ name: document.getElementById('id_directory_name2').value}) // This is your file object
        }).then(
          response => response.json() // if the response is a JSON object
        ).then(
          (json) => {
            message(json.info, "info")
            if(json.info == 'Folder Created Sucessfully'){
              create_ui(json.dir, json.directory_name, true)
            }
            $('#close_create').trigger('click')
            console.log(json)
          }
        ).catch(
          error => console.log(error) // Handle the error response object
        );
      };
    


    function delete_node(node){
        node.preventDefault()
        var parent_node = node.currentTarget.parentNode
        var str = "#name"+parent_node.id
        var confirm = window.confirm("Are You Sure You Want To Delete "+$(str).text()+"?")
        if(confirm){
            //delete_node
            fetch('/api/'+parent_node.id, { // Your DELETE endpoint
                method: 'DELETE',
                headers: {
                  "X-CSRFToken": token,
                  "Accept":'application/json',
                }
              }).then(
                response => response.json() // if the response is a JSON object
              ).then(
                (json) => {
                  message(json, "info")
                  console.log("delete")
                  if(json = "Folder Deleted Successfully"){
                      parent_node.remove()
                      console.log("deleted node ",parent_node.id)
                  }
                  
                }
              ).catch(
                error => console.log(error) // Handle the error response object
              );
            
        }
    }

    function navigate(event, link){
        event.preventDefault();
        window.location.href = link;
    }

    function message(msg, tag){
        var node_html = `<li class="text-center alert alert-${tag}">
            ${msg}
            <span id='close' class="fas fa-times-circle" onclick='this.parentNode.parentNode.removeChild(this.parentNode)'></span>
        </li>`

        var id = document.getElementById('msg_arr')
        id.innerHTML += node_html
    }

    function create_ui(dir, directory_name, is_directory){
      var folder = `
      <div id="${dir}" ondblclick="navigate(event,'/dashboard/${dir}')" class="glass box">
        <div onclick="delete_node(event)" class="delete fas fa-times-circle" style="margin-bottom:20px;"></div>
        <span class="fas fa-folder"></span>
        <div style="text-transform:capitalize;" id="name${dir}">${directory_name}</div>
      </div>
    `
    var image = `
    <div id="${dir}" ondblclick="navigate(event,'/edit/${dir}')" class="glass box bg-primary text-white">
      <div onclick="delete_node(event)" class="delete fas fa-times-circle" style="margin-bottom:20px;color:tomato"></div>
      <span class=" fas fa-file"></span>
      <div style="text-transform:capitalize;" id="name${dir}">${directory_name}</div>
    </div>
    `

    if(is_directory == true){
      document.getElementById('main').innerHTML += folder
    }
    else{
      document.getElementById('main').innerHTML += image
    }
    }
</script>

{% endblock %}

templates/edit.html
{% extends "header.html" %}

{% block content %} 

{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.11/cropper.min.css" integrity="sha512-NCJ1O5tCMq4DK670CblvRiob3bb5PAxJ7MALAz2cV40T9RgNMrJSAwJKy0oz20Wu7TDn9Z2WnveirOeHmpaIlA==" crossorigin="anonymous" />
<style>
    /* Ensure the size of the image fit the container perfectly */
    body{
        background: rgb(39, 39, 39);
        background-size:200% 200%;
    }
    #crop-id {
        display: block;
    
        /* This rule is very important, please don't ignore this */
        max-width: 100%;
    }
    .icon-bar {
        width: auto;
        background-color: rgb(68, 68, 68);
        transform: translate(-50%,-50%);
        left:50%;
        top:5%;
        position:fixed;
        z-index:10;
      }
      .bottom-bar {
        background-color: rgb(68, 68, 68);
        z-index:10;
      }
      .bottom-bar > div{
          margin:0 10px;
      }
      
      .icon-bar a {
        float: left;
        width: 50px;
        text-align: center;
        padding: 12px 0;
        transition: all 0.3s ease;
        color: white;
      }
      
      .icon-bar a:hover {
        background-color: rgb(175, 175, 175);
      }
      
      .agree {
        background-color: green;
      }
      .cancel{
          background-color: red;
      }

      .settings-box{
        background-color: rgb(68, 68, 68);
        border-radius:15px;
        padding:20px;
        margin-top:10px;
      }


</style>
<div>
	<div style="margin-top:20px;">
		<div class="">
            <div>
                <div class="col-md-12 text-center text-white">
                    <h3>Editor</h3>
                </div>
                <div class="d-flex justify-content-center align-items-center">
                    
                    <div class="settings-box"style="max-width:100%;">
                        <img id="crop-id" style="max-height:80vh;" src="{{image.image_path.url}}">
                    </div>
                </div>
                
            </div>
			<div>
                <img id="base" style="display:none;" src="{{image.image_path.url}}">
            </div>

                
            </div>
            <div class="row text-white mt-4 mb-5">
                <div class="col-md-8 container mt-3">
                    <div class="d-flex align-items-center settings-box justify-content-around">
                        <span>Brightness</span><input type="range" min=-1 max=1 step=0.1 class="form-range flex-grow-1 col-md-6" onchange="update(event)" id="Brightness">
                    </div>
                    <div class="d-flex align-items-center settings-box justify-content-around">
                        <span>Saturation</span><input type="range" min=0 max=1 step=0.1 value=1 class="form-range flex-grow-1 col-md-6" onchange="update(event)" id="Saturation">
                    </div>
                    <div class="d-flex align-items-center settings-box justify-content-around">
                        <span>Contrast</span><input type="range" min=-1 max=1 step=0.1 class="form-range flex-grow-1 col-md-6" onchange="update(event)" id="Contrast">
                    </div>
                    <div class="d-flex align-items-center settings-box justify-content-around">
                        <span>Vingette</span><input type="range" min=0 max=1 step=0.1 value=0 class="form-range flex-grow-1 col-md-6" onchange="update(event)" id="Vingette">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class=" d-flex flex-column justify-content-center align-items-center settings-box mt-3">
                        <div class="btn btn-lg btn-primary" style="font-size:15px;" onclick="create()"><span  class="fas fa-cut"></span> Crop</div>
                        <div class="btn btn-lg bg-white mt-2" style="font-size:15px;" id="B&W" onclick="update(event)"><span class="fas fa-tint-slash"></span> B&W</div>
                        <div class="btn btn-lg btn-warning mt-2" style="font-size:15px;" id="Sepia" onclick="update(event)"><span class="fas fa-tint"></span> Sepia</div>
                        

                    </div>
                    <div class="d-flex flex-row justify-content-around settings-box mt-4">
                        <div class="btn btn-lg btn-success" style="font-size:15px;" onclick="upload_image()"><span class="fas fa-check"></span> Save</div>
                        <div class="btn btn-lg btn-danger" style="font-size:15px;" onclick="window.history.back()"><span class="fas fa-times"></span> Cancel</div>
                    </div>

                    
                </div>
                <div class="d-flex flex-row justify-content-center align-items-center settings-box mx-auto">
                    <div class="col-md-12 btn btn-lg btn-success" style="font-size:15px;" onclick="save_image()"><span class="fas fa-download"></span> Download</div>
                </div>
                
        
            </div>
		</div>
		
	</div>
</div>

<div class="icon-bar" id="toolbar" style="display:none;">
    <a onclick="cropper.zoom(-0.1);"><i class="fas fa-search-minus"></i></a> 
    <a onclick="cropper.zoom(0.1);"><i class="fas fa-search-plus"></i></a> 
    <a onclick="scale_h()"><i class="fas fa-arrows-alt-h"></i></a> 
    <a onclick="scale_v()"><i class="fas fa-arrows-alt-v"></i></a> 
    <a onclick="cropper.rotate(-90)"><i class="fas fa-undo"></i></a> 
    <a onclick="cropper.rotate(90)"><i class="fas fa-redo"></i></a> 
    <a class="cancel" onclick="remove_cropper()"><i class="fa fa-times-circle"></i></a> 
    <a class="agree" onclick="crop()" ><i class="fa fa-check-circle"></i></a> 
</div>

<script src="{% static 'js/vintage.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.11/cropper.min.js" integrity="sha512-FHa4dxvEkSR0LOFH/iFH0iSqlYHf/iTwLc5Ws/1Su1W90X0qnxFxciJimoue/zyOA/+Qz/XQmmKqjbubAAzpkA==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.0/FileSaver.min.js" integrity="sha512-csNcFYJniKjJxRWRV1R7fvnXrycHP6qDR21mgz1ZP55xY5d+aHLfo9/FcGDQLfn2IfngbAHd8LdfsagcCqgTcQ==" crossorigin="anonymous"></script>


<script>
    var cropper;
    var h = 1;
    var v = 1;
    var defaults = {
        width: 160,
        height: 90,
        minWidth: 256,
        minHeight: 256,
        maxWidth: 4096,
        maxHeight: 4096,
        fillColor: '#fff',
        imageSmoothingEnabled: false,
        imageSmoothingQuality: 'high',
    }

    var effects = {
        vignette: 0, //0 to 1 default 0
        brightness: 0,  //-1 to 1
        saturation:1, // 0 to 1
        contrast:0,  //-1 to 1
        sepia: false,
        gray:false,
        
    };

    const srcEl = document.getElementById('crop-id');
    const baseData = document.getElementById('base');


    function create(){
        document.getElementById('toolbar').style.display = "block"
        const image = document.getElementById('crop-id');
        cropper = new Cropper(image, {
            aspectRatio: 16 / 9,
        });
    }

    function scale_h(){
        if(h){
            cropper.scale(-1, 1);
            h = 0;
        }
        else{
            cropper.scale(1, 1);
            h = 1;
        }
        
    }

    function scale_v(){
        if(v){
            cropper.scale(1, -1);
            v = 0;
        }
        else{
            cropper.scale(1, 1);
            v = 1;
        }
        
    }

    function remove_cropper() {
        document.getElementById('toolbar').style.display = "none"
        cropper.scale(-1);
        cropper.destroy()
    }

    function crop(){
        console.log(cropper.getData())
        cropper.getCroppedCanvas(defaults).toBlob((blob) => {
            
            srcEl.src = URL.createObjectURL(blob);
            baseData.src = URL.createObjectURL(blob);
            remove_cropper()
        })
    }
    
    

    function update(event){
        
        if(event.target.id == "Brightness"){
            effects.brightness = Number(event.target.value)
        }
        else if(event.target.id == "Saturation"){
            effects.saturation = Number(event.target.value)
        }
        else if(event.target.id == "Contrast"){
            effects.contrast = Number(event.target.value)
        }
        else if(event.target.id == "Vingette"){
            effects.vignette = Number(event.target.value)
        }
        else if(event.target.id == "Sepia"){
            if(effects.sepia == false){
                effects.sepia = true
            } 
            else{
                effects.sepia = false
            }
        }
        else if(event.target.id == "B&W"){
            if(effects.gray == false){
                effects.gray = true
            } 
            else{
                effects.gray = false
            }
        }

        else{
            console.log("sike")
        }
        vintagejs(baseData, effects)
        .then(res => {
            srcEl.src = res.getDataURL()
        });
    }

    function save_image(){
        // Must use FileSaver.js 2.0.2 because 2.0.3 has issues.

        let imagePath = srcEl.getAttribute('src');
        let fileName = getFileName(imagePath);
        saveAs(imagePath, fileName); 
        
    }

    function getFileName(str) {
        return "download"
    }


    var upload_file_url = "/edit/api/{{home_dir.pk}}"
    var token = '{{csrf_token}}';
    var formData = new FormData()

    const upload_image = () => {

        formData.append("directory_name", "{{home_dir.directory_name}}")

        var c = document.createElement("canvas");
        var ctx = c.getContext("2d");
        var results;
        c.width = srcEl.naturalWidth;     // update canvas size to match image
        c.height = srcEl.naturalHeight;
        ctx.drawImage(srcEl, 0, 0);       // draw in image
        c.toBlob(function(blob) {        // get content as JPEG blob
            results = blob
            console.log(results)
        
        var blob = new Blob([results], {type : 'image/png'});
        var fileOfBlob = new File([blob], 'modified_image.png');
        formData.append("image_path", fileOfBlob)
        console.log(formData);

        fetch(upload_file_url, { // Your POST endpoint
          method: 'POST',
          headers: {
            "X-CSRFToken": token,
            "Accept":'application/json',
          },
          body: formData // This is your file object
        }).then(
          response => response.json() // if the response is a JSON object
        ).then(
          (json) => {
                message(json, "info")
                $('#close_upload').trigger('click')
                console.log(json)
          }
        ).catch(
          error => console.log(error) // Handle the error response object
        );
        }, "image/png", 0.75);

        
      };

      function message(msg, tag){
        var node_html = `<li class="text-center alert alert-${tag}">
            ${msg}
            <span id='close' class="fas fa-times-circle" onclick='this.parentNode.parentNode.removeChild(this.parentNode)'></span>
        </li>`

        var id = document.getElementById('msg_arr')
        id.innerHTML += node_html
    }
</script>
{% endblock %}

templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%if title %}
        <title>PIXLR - {{title}}</title>
    {% else %}
        <title>PIXLR</title>
    {% endif %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</head>
<body>
    <style>
        body{
            background: linear-gradient(0deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
            background-size:200% 200%;
        }
        .messages{
            position:fixed;
            transform: translate(-50%,0%);
            top:15px;
            left:50%;
            
        }
    </style>
        <div id="msg_arr" class="messages col-xs-6" style="list-style-type:none;z-index:10;">
            
            {% for message in messages %}
            <li {% if message.tags %} class="text-center alert alert-{{ message.tags }}"{% endif %}>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Note: {% endif %}
                {{ message }}
                <span id='close' class="fas fa-times-circle" onclick='this.parentNode.parentNode.removeChild(this.parentNode)'></span>
            </li>
            {% endfor %}
            
        </div>
    
    {% block content %} 

    {% endblock %} 
    
</body>
</html>

templates/login.html
{% extends "header.html" %}

{% block content %} 

{% load static %}
{% load crispy_forms_tags %}         

<div style="margin-top:5%;">
	<div class="container" >
		<div class="col-md-8 mx-auto glass">
			<div class="row">
				<img class="img-fluid mt-5 mx-auto" style="height:100px;" src="{% static 'img/lens2.png' %}" alt="LOGO">
			</div>
			
			<div class="container py-5">

				<h1 class="text-center">Login</h1>

				<form method="POST">
					{% csrf_token %}
					{{ login_form|crispy }}                 
					<button class="btn btn-primary" type="submit">Login</button>
				</form>
				<p class="text-center mt-4">Don't have an account?<a href="{% url 'register' %}"> Register</a> instead.</p>
			</div>
		</div>
	</div>
</div>



{% endblock %}

templates/logout.html
{% extends "header.html" %}

{% block content %} 

{% load static %}
{% load crispy_forms_tags %}         

<div style="margin-top:5%;">
	<div class="container " >
		<div class="col-md-8 glass mx-auto">
			<div class="col-md-2 mx-auto">
				<img class="img-fluid mt-5" src="{% static 'img/lens2.png' %}" alt="LOGO">
			</div>
			
			<div class="container py-5">

				<h1 class="text-center">You have Been Logged Out Successfully!</h1>
                <p class="text-center mt-4">To Log back In Click On<a href="{% url 'login' %}"> Login</a></p>
				
			</div>
		</div>
	</div>
</div>



{% endblock %}